### ISSUE TITLE
Exporting .obj with high vertex count fails

### ISSUE THREAD

**Issue by guzzard** [stephomi/sculptgl#42]
When trying to export an object as .obj with vertex count 3 424 770 it fails with this error in the console.

[15157:0803/161750:ERROR:nw_shell.cc(335)] RangeError: Invalid string length
    at Object.g.addMesh (file:///tmp/.org.chromium.Chromium.3ad4ro/sculptgl.min.js:11:17294)
    at Object.g.exportOBJ (file:///tmp/.org.chromium.Chromium.3ad4ro/sculptgl.min.js:11:15551)
    at Object.g.saveFileAsOBJ (file:///tmp/.org.chromium.Chromium.3ad4ro/sculptgl.min.js:11:24691)
    at Object.f._onClick (file:///tmp/.org.chromium.Chromium.3ad4ro/sculptgl.min.js:3:31103)
[15157:0803/161750:INFO:CONSOLE(11)] "Uncaught RangeError: Invalid string length", source: file:///tmp/.org.chromium.Chromium.3ad4ro/sculptgl.min.js (11)

When going down one level to 856 194 vertices exporting works fine without any error in the console.

**Comment by stephomi** [comment]
I'm afraid it's a browser memory limitation and I can't do anything about that.

OBJ is a text format, so it's not really performant/memory friendly when exporting.

If you find a browser app that can export a >~5M vertices model, I'd be interested to know more :)
